# EEG Transformer 训练配置文件
# 数据路径配置
output_dir: "./train_output"

# 训练参数
lr: 0.0003
epochs: 40
batch_size: 64

# 设备配置
device: "cuda:1"

# 实验配置
insubject: true
encoder_type: "ATMS"

# 受试者列表
subjects:
  # - "sub-01"
  # - "sub-02"
  # - "sub-03"
  # - "sub-04"
  # - "sub-05"
  # - "sub-06"
  # - "sub-07"
  - "sub-08"
  # - "sub-09"
  # - "sub-10"
